routes:
  /news:
    version: 1
    methods:
      GET:
        public: true
        response: News-Collection
        action: News-Collection
      POST:
        public: false
        request: News-Entity
        response: Passthru
        action: News-Insert
schema:
  News-Collection: !include resources/schema/news/collection.json
  News-Entity: !include resources/schema/news/entity.json
action:
  News-Collection:
    class: Fusio\Custom\Action\News\Collection
  News-Insert:
    class: Fusio\Custom\Action\News\Insert
connection:
  Acme-Mysql:
    class: Fusio\Adapter\Sql\Connection\Sql
    config:
      type: pdo_mysql
      host: localhost
      username: root
      password: 
      database: fusio
migration:
  Acme-Mysql:
    - resources/sql/v1_schema.sql
