routes:
  "/todo/:todo_id":
    version: 1
    methods:
      GET:
        public: true
        response: Todo
        action: Todo-Row
      DELETE:
        public: false
        request: Passthru
        response: Todo-Message
        action: Todo-Delete
  "/todo":
    version: 1
    methods:
      GET:
        public: true
        response: Todo-Collection
        action: Todo-List
      POST:
        public: false
        request: Todo
        response: Todo-Message
        action: Todo-Insert
schema:
  Todo: !include resources/schema/todo/entity.json
  Todo-Collection: !include resources/schema/todo/collection.json
  Todo-Message: !include resources/schema/todo/message.json
action:
  Todo-List:
    class: Fusio\Custom\Action\Todo\Collection
  Todo-Row:
    class: Fusio\Custom\Action\Todo\Row
  Todo-Insert:
    class: Fusio\Custom\Action\Todo\Insert
  Todo-Delete:
    class: Fusio\Custom\Action\Todo\Delete
connection:
  Default-Connection:
    class: Fusio\Adapter\Sql\Connection\SqlAdvanced
    config:
      url: "sqlite:///${dir.cache}/todo-app.db"
migration:
  Default-Connection:
    - resources/sql/v1_schema.sql
