routes:
  "/todo/:todo_id":
    version: 1
    methods:
      GET:
        public: true
        response: Todo
        action: Fusio\Custom\Action\Todo\Row
      DELETE:
        public: false
        request: Passthru
        response: Todo-Message
        action: Fusio\Custom\Action\Todo\Delete
  "/todo":
    version: 1
    methods:
      GET:
        public: true
        response: Fusio\Custom\Action\Todo\Collection
        action: Todo-List
      POST:
        public: false
        request: Todo
        response: Todo-Message
        action: Fusio\Custom\Action\Todo\Insert
schema:
  Todo: !include resources/schema/todo/entity.json
  Todo-Collection: !include resources/schema/todo/collection.json
  Todo-Message: !include resources/schema/todo/message.json
connection:
  Default-Connection:
    class: Fusio\Adapter\Sql\Connection\SqlAdvanced
    config:
      url: "sqlite:///${dir.cache}/todo-app.db"
migration:
  Default-Connection:
    - resources/sql/v1_schema.sql
