language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - nightly
  - hhvm
matrix:
    allow_failures:
        - php: nightly
services:
  - mysql
  - memcached
before_install:
  - if [[ "$TRAVIS_PHP_VERSION" != "nightly" ]] && [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then phpenv config-rm xdebug.ini; fi;
install:
  - composer install
before_script:
  - if [ $DB = 'mysql' ]; then mysql -e 'create database fusio;'; fi;
script:
  - vendor/bin/phpunit
env:
  - DB=mysql
  - DB=sqlite
