language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - nightly
  - hhvm
matrix:
    allow_failures:
        - php: nightly
services:
  - mysql
  - memcached
before_install:
  - if [[ "$TRAVIS_PHP_VERSION" != "nightly" ]] && [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then phpenv config-rm xdebug.ini; fi;
install:
  - composer install
  - npm install -g protractor
before_script:
  - if [ $DB = 'mysql' ]; then mysql -e 'create database fusio;'; fi;
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - webdriver-manager update
  - webdriver-manager start &
  - cd public && php -S 127.0.0.1:8008 server.php &
  - php public/server.php --warmup
  - sleep 4
script:
  - vendor/bin/phpunit
  - cd public && protractor conf.js
env:
  - DB=mysql
  - DB=sqlite
