language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - nightly
  - hhvm
matrix:
    allow_failures:
        - php: nightly
services:
  - mysql
  - memcached
before_install:
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then phpenv config-add tests/config.ini; fi;
  - if [ "$TRAVIS_PHP_VERSION" != "nightly" ] && [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then phpenv config-rm xdebug.ini; fi;
install:
  - composer install
  - cd public
  - npm install bower
  - node node_modules/bower/bin/bower install
  - npm install grunt
  - npm install grunt-contrib-concat
  - npm install grunt-contrib-uglify
  - npm install grunt-contrib-cssmin
  - npm install grunt-angular-templates
  - npm install grunt-cli
  - node node_modules/grunt-cli/bin/grunt
  - npm install protractor
  - node node_modules/protractor/bin/webdriver-manager update
  - cd ..
before_script:
  - if [ $DB = 'mysql' ]; then mysql -e 'create database fusio;'; fi;
  - if [ $DB = 'mysql' ]; then mysql -e 'create database fusio_ui;'; fi;
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - cd public
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php server.php --warmup; fi;
  - ( if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php -S 127.0.0.1:8008 server.php; fi; ) &
  - ( if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then node node_modules/protractor/bin/webdriver-manager start; fi; ) &
  - sleep 4
  - cd ..
script:
  - vendor/bin/phpunit
  - ( if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then cd public/tests && protractor conf.js; fi; )
env:
  - DB=mysql
  - DB=sqlite
