language: php
php:
  - 7.3
  - 7.4
  - 8.0
sudo: false
services:
  - mysql
before_install:
  - mysql -e 'create database fusio;'
install:
  - composer install
  - php bin/fusio install --no-interaction
before_script:
  - php bin/fusio deploy
  - php bin/fusio migration:migrate --connection=System --no-interaction
script:
  - vendor/bin/phpunit
