version: '0.6'
description: 'The backend app to administrator and configure the system.'
screenshot: 'https://raw.githubusercontent.com/apioo/fusio/master/doc/_static/backend.png'
website: 'https://github.com/apioo/fusio-backend'
downloadUrl: 'https://www.fusio-project.org/marketplace/fusio.zip'
sha1Hash: 'de93335ba3b8f5b171aff8214249b5bcbf796a2b'
